Implemented task 1

diff --git a/factors b/factors
--- a/factors
+++ b/factors
@@ -1,11 +1,29 @@
 #!/bin/bash
-# Script to factorize numbers into two smaller numbers
+# Script to factor numbers into two factors
+
+if [ -z "$1" ]; then
+  echo "Usage: ./factors <input_file>"
+  exit 1
+fi
 
 while read -r number; do
-  for ((i=2; i<=number/2; i++)); do
-    if (( number % i == 0 )); then
+  if ! [[ "$number" =~ ^[0-9]+$ ]]; then
+    echo "Skipping invalid input: $number"
+    continue
+  fi
+
+  found=0
+  for ((i = 2; i <= number / 2; i++)); do
+    if ((number % i == 0)); then
       echo "$number=$i*$(($number / i))"
+      found=1
       break
     fi
   done
+
+  # If no factor found, print that number is a prime
+  if [[ $found -eq 0 ]]; then
+    echo "$number is prime or unable to factor"
+  fi
+
 done < "$1"
